### ISSUE TITLE
Hubot Login to Grafana to fetch PNG

### ISSUE THREAD

**Issue by ChristianKniep** [stephenyeargin/hubot-grafana#23]
Hey there,

I am doodling around with hubot-rocketchat and I am quite far.
Thing is, that if I query for a graph only the link is put into the chat. I guess that's how it's supposed to work, the rocketchat code should evaluate the link to present the actual picture.
When clicking the link I get to the Login-Page. I suppose that's the issue here: 
The PNG could not be fetched since it's behind the 'login'. Am I right.

**Comment by Tenzer** [comment]
I am guessing you haven't set up the [S3 integration](https://github.com/stephenyeargin/hubot-grafana#configuration-variables)? If you don't do that Hubot will only be able to post a link to the graph, since it doesn't have anywhere to upload the image to. (Hubot doesn't support sending images to the chat, since not all networks support that.)

If you are able to get S3 access set up, Hubot will instead get the image from Grafana, upload it to S3 and post the link to that file on your network of choice, along with the link to the graph in Grafana.

**Comment by ChristianKniep** [comment]
Hmm... OK, one way could be to push the PNG over S3, but wouldn't it also be possible to 
paste the link and let the chat-server do the resolvement of it?
I suppose that's how img-resolution is done. Checke the mime-type, if it's an image download and display it.

**Comment by stephenyeargin** [comment]
@ChristianKniep I don't think that would work as expected. The authentication header (via an API key) is appended [here](https://github.com/stephenyeargin/hubot-grafana/blob/master/src/grafana.coffee#L235-L239) in the code. I know that later versions of Grafana has a snapshot publishing function (that will upload the snapshot to the server that is likely still behind the firewall), but I don't think that's exposed via the API.

**Comment by eMerzh** [comment]
Isn't possible to use the sharing?  http://docs.grafana.org/reference/sharing/ 

as described here https://github.com/grafana/grafana/issues/2729

**Comment by ChristianKniep** [comment]
@eMerzh Good idea, but I am not sure if that will cut it. 
AFAI understood it, the chat servers expect URL pointing to certain mime-types to preview the chart.
For me it's Rocket.Chat and they just preview png and off they go. 
But I haven't looked at it to close, since I am busy with something else and this topic got a bit postponed.

But one thing is a bit cumbersome: The shared dashboards have to be created by hand and the reference is a long hash instead of a nice human redable name, even though that might be cached somewhere... Hmm...

**Comment by andrzejwp** [comment]
+1, I'm using Rocket.Chat too, and it's fairly simple to pass a shared PNG, check out the following integration:

```
var imageUrl = util.format('https://grafana.xxx/render/dashboard-solo/db/time-logs?panelId=5&fullscreen&width=500&almightyPotatoSalad=%d', (new Date()).getTime());
request.post('https://rocket.chat.xxx/hooks/integration_token', {
    form: {
      "text": "Friendly graph",
      "attachments": [{
        "title": "Look at the graph!",
        "title_link": "google.com",
        "text": "",
        "image_url": imageUrl,
        "color": "#764FA5"
      }]
    }
  },
  function (error, response, body) {}); 

```

**Comment by andrzejwp** [comment]
Anything we can do about this?

**Comment by gentunian** [comment]
Why you restrict this to S3 and not any static web server? Do they pay you for that? :D

**Comment by gentunian** [comment]
Ok, this is my hack in order to not use S3 or any web server:

define a new  environment variable: `HUBOT_SLACK_URL=https://myteam.slack.com`

And use the below instead the `fetchAndUpload` function:

```
    hubot_slack_token = process.env.HUBOT_SLACK_TOKEN
    slackUrl = process.env.HUBOT_SLACK_URL

    request url, requestHeaders, (err, res, body) ->
      tempFile = '/tmp/' + #{crypto.randomBytes(20).toString('hex')}.png
      fs.writeFileSync tempFile , body
      request.post({
        url: slackUrl + '/api/files.upload'
        formData:
          channels: '@sebastiantreu'
          token: hubot_slack_token
          file: fs.createReadStream tempFile         
      }, (err, httpResponse, body) ->
        if err
          robot.logger.error err
      )
```

Done. No need for external web servers. Just upload the file into slack.

# TODO:
Avoid using a temporal file. I'm not familiar with nodejs development. It would be nice to use `body` directly into the `request.post` as file. I didn't find how.

**Comment by stephenyeargin** [comment]
@gentunian

> Why you restrict this to S3 and not any static web server? Do they pay you for that? :D

S3 was the easiest tool to reach for and fairly ubiquitous / inexpensive. If they are paying me, I should get them my new address. 😄 

>Ok, this is my hack in order to not use S3 or any web server: [...]

This is cool, but the package is written on purpose to be (mostly) agnostic about what service it connects to, be it RocketChat, HipChat, IRC, Slack, etc. For this bit, I'd suggest a few things:

- [ ] Open the [change as a PR](https://help.github.com/articles/about-pull-requests/), so the collaborators can review it and you get credit for the change.
- [ ] Switch based on whether S3 is configured. If not, fall back to the proposed method of uploading to Slack (if `isSlack` evaluates to true).
- [ ] Ensure in all cases the final fallback is to return the internal link to Grafana.

**Comment by gentunian** [comment]
@stephenyeargin great you understood the joke :) after posting I was afraid I could offend you.

Thanks for suggestions !

**Comment by stephenyeargin** [comment]
So, we have Slack uploads as of #58 landing and Rocket.chat as of #70, so I think this is effectively taken care of. The patterns are in the code if another service is desired, or we want to augment it.
